name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.18.0'

    - name: Install dependencies
      run: npm install

    - name: Send Lark Notification (Success)
      if: success()
      run: |
        curl -X POST "${{ secrets.DPLOI_LARK_BOT_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d '{
            "msg_type": "post",
            "content": {
              "post": {
                "en_us": {
                  "title": "SUCCESSFUL DEPLOYMENT NOTIFICATION✅",
                  "content": [
                    [
                      {
                      "tag": "text",
                      "text": "Deployment successful!"
                      }
                    ],
                    [
                      {
                      "tag": "a",
                      "text": "View Website",
                      "href": "https://mayan.com.ph"
                      }
                    ]
                  ]
                }
              }
            }
          }'

    - name: Send Lark Notification (Failure)
      if: failure()
      run: |
        curl -X POST "${{ secrets.DPLOI_LARK_BOT_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d '{
            "msg_type": "post",
            "content": {
              "post": {
                "en_us": {
                  "title": "DEPLOYMENT ERROR NOTIFICATION❌",
                  "content": [
                    [
                      {
                      "tag": "text",
                      "text": "Deployment Failed!"
                      }
                    ],
                    [
                      {
                      "tag": "a",
                      "text": "Deployment Log",
                      "href": "https://vercel.com/itsyahboilaurences-projects/mayan-marketing-website"
                      }
                    ]
                  ]
                }
              }
            }
          }'
